---
- name: Create htpasswd
  file:
    path: "/etc/squid"
    state: "directory"
    owner: "root"
    group: "root"
  become: true

- name: Generate passwd
  shell: htpasswd -c -b /etc/squid/passwd '{{ proxy_user_ }}' '{{ proxy_pass_ }}'
  become: true
