---
- name: redhat | Installing Squid (Non-Fedora)
  yum:
    name: "{{ squid_package }}"
    state: "present"
  become: true
  when: ansible_distribution != "Fedora"

- name: Install the httpd-tools
  yum:
    name: httpd-tools
    state: present
  when: ansible_distribution != "Fedora"
